# Generated by Django 5.2.8 on 2025-11-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Foto')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível no Site?')),
            ],
        ),
    ]
